# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

#### Autor: Evandro Avellar

In [30]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.7.9


In [31]:
import numpy as np

### Exercícios Sobre Módulos Python Para Análise de Dados

### Exercício 1

* Crie um array NumPy com 1000000 e uma lista com 1000000.
* Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
* Qual objeto oferece melhor performance, array NumPy ou lista?

In [32]:
vetor = np.arange(1000000)
len(vetor)

1000000

In [36]:
lista = list(range(1000000))
len(lista)

1000000

In [37]:
%time vetor2 = vetor * 2

Wall time: 4.5 ms


In [38]:
%time lista = [x * 2 for x in lista]

Wall time: 193 ms


### Exercício 2

* Crie um array de 10 elementos
* Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [39]:
vetor3 = np.arange(10)
vetor3[5:9] = 0
vetor3

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 9])

### Exercício 3

* Crie um array de 3 dimensões e imprima a dimensão 1 

In [40]:
cubo = np.random.randint(1, 100, (4, 3, 3))
print(f'O array cubo tem {cubo.ndim} dimensões.')
cubo

O array cubo tem 3 dimensões.


array([[[60,  6, 34],
        [10, 94, 87],
        [59, 75, 95]],

       [[45, 69, 51],
        [23, 76, 16],
        [87, 39, 17]],

       [[13, 41, 25],
        [83, 44, 18],
        [12, 26, 99]],

       [[20, 45, 95],
        [47, 98, 24],
        [14, 52, 62]]])

In [41]:
vetor = cubo[1,0]
print(f'O array vetor tem {vetor.ndim} dimensão.')
vetor

O array vetor tem 1 dimensão.


array([45, 69, 51])

### Exercício 4

* Crie um array de duas dimensões (matriz).
* Imprima os elementos da terceira linha da matriz
* Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [42]:
# Array de duas dimensões
matriz = np.random.randint(1, 100, (4, 3))
print(f'O array matriz tem {matriz.ndim} dimensões.')
matriz

O array matriz tem 2 dimensões.


array([[38, 35, 43],
       [70, 77, 79],
       [37, 55, 34],
       [19, 70, 41]])

In [43]:
# Terceira linha
matriz[2]

array([37, 55, 34])

In [44]:
# Todos os elementos da primeira e segunda linhas e segunda e terceira colunas
matriz[0:2, 1:3]

array([[35, 43],
       [77, 79]])

### Exercício 5

In [45]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [47]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. 
# Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [48]:
grupo = zip(xarr, yarr, cond)
for i in grupo:
    if i[2]:
        print(i[0])
    else:
        print(i[1])

1.1
2.2
1.3
1.4
2.5


### Exercício 7

In [49]:
import pandas as pd

In [97]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

In [50]:
# Criando array A
A = np.random.randint(1, 100, (10,))
A


array([31, 42, 57, 28, 45, 59, 41, 58, 16, 28])

In [51]:
# Salvando num arquivo
np.savetxt('out.npy', A, newline='\n')

In [52]:
# lendo um arquivo e carregando no Array B
B = A = np.loadtxt('out.npy', dtype=int) 
B

array([31, 42, 57, 28, 45, 59, 41, 58, 16, 28])

### Exercício 8

In [53]:
# Considerando a série abaixo, imprima os valores únicos na série
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [ ]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

In [134]:
json_load = resp.json()
data3 = pd.DataFrame(json_load)
data3.columns

Index(['url', 'repository_url', 'labels_url', 'comments_url', 'events_url',
       'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels',
       'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments',
       'created_at', 'updated_at', 'closed_at', 'author_association',
       'active_lock_reason', 'draft', 'pull_request', 'body', 'reactions',
       'timeline_url', 'performed_via_github_app'],
      dtype='object')

In [137]:
data3[['number','title','labels','state']]

number                                              title  \
0    44605  DEP: df.insert not showing warning for allow_d...   
1    44604  ASV: reduce overall run time for GroupByMethod...   
2    44603  BUG: DataFrame eval will not work with 'Timest...   
3    44602  BUG: na_value = None in ExtensionDtype causes ...   
4    44601          [DON'T MERGE] Try debug CI (test_eval.py)   
5    44600      CLN: Remove duplicate skip windows decorators   
6    44599  BUG: parse_dates=False while passing date_pars...   
7    44598             BUG: concat_compat with 2D PeriodArray   
8    44597       API/DEPR: int downcasting in DataFrame.where   
9    44596  CI: Add single CPU core build for pytest.mark....   
10   44594  PERF: improve find_common_type perf for specia...   
11   44590  CI: docstring check failing with Segmentation ...   
12   44589          ENH: add indexing syntax to GroupBy.nth()   
13   44588  BUG: join MultiIndex with overlapping Interval...   
14   44587  REF: remove always-True DataFrame._iset_item k...   
15   44585    BUG: Series.where with IntervalDtype when no-op   
16   44584  CI: No single CPU builds for pytest.mark.singl...   
17   44582        BUG: Series.mode with dt64tz or PeriodDtype   
18   44581        BUG: Series.view from int64 to datetimelike   
19   44580                      Deprecate skipna=None for mad   
20   44578  BUG: Series.reset_index not ignoring name with...   
21   44576            Holiday rename; Juneteenth `start_date`   
22   44575  BUG: `name` argument in `Series.reset_index` b...   
23   44574                            ENH: Juneteenth holiday   
24   44569  DOC: update shared_docs to clarify groupby wit...   
25   44568       ENH: Multiple character separators in to_csv   
26   44567                      DOC: GL01 numpydoc validation   
27   44564  BUG: DataFrame.shift with axis=1 and mismatche...   
28   44562  PERF/BUG: ensure we store contiguous arrays in...   
29   44559  PERF: avoid copy in concatenate_array_managers...   

                                               labels state  
0                                                  []  open  
1   [{'id': 732775912, 'node_id': 'MDU6TGFiZWw3MzI...  open  
2   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
3   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
4                                                  []  open  
5   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
6                                                  []  open  
7                                                  []  open  
8   [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
9                                                  []  open  
10  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open  
11                                                 []  open  
12  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
13                                                 []  open  
14                                                 []  open  
15                                                 []  open  
16  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open  
17                                                 []  open  
18                                                 []  open  
19  [{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...  open  
20                                                 []  open  
21  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
22  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
23  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
24                                                 []  open  
25  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
26  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
27                                                 []  open  
28  [{'id': 3165546917, 'node_id': 'MDU6TGFiZWwzMT...  open  
29  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open

### Exercício 10

In [1]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
import random
import time
import datetime

In [27]:
# Criando uma conexão
conn = sqlite3.connect('banco_3.db')   

# Criando um cursor
c = conn.cursor()
 
# Função para criar uma tabela
def create_table():
    c.execute('CREATE TABLE IF NOT EXISTS produtos(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, date TEXT, '\
              'prod_name TEXT, valor REAL)')
    
# Usando variáveis para inserir dados    
produtos = ['teclado', 'mouse', 'monitor', 'gabinete', 'memória', 'SSD']

def data_insert_var():
    new_date = datetime.datetime.now()
    new_prod_name = random.choice(produtos)
    new_valor = random.randrange(50,100)
    c.execute("INSERT INTO produtos (date, prod_name, valor) VALUES (?, ?, ?)", 
              (new_date, new_prod_name, new_valor))
    conn.commit()
    
# Leitura de dados
def leitura_todos_dados():
    c.execute("SELECT * FROM PRODUTOS")
    for linha in c.fetchall():
        print(linha)


# Cria Data Frame a partir da consulta
def cria_data_frame():
    c.execute("SELECT * FROM PRODUTOS")
    df = pd.DataFrame(c.fetchall())
    return df


In [11]:
# Cria a tabela
create_table()

In [12]:
for n in range(20):
    data_insert_var()

In [28]:
leitura_todos_dados()


(1, '2021-11-24 16:25:56.983730', 'monitor', 84.0)
(2, '2021-11-24 16:25:57.074294', 'teclado', 51.0)
(3, '2021-11-24 16:25:57.118325', 'gabinete', 80.0)
(4, '2021-11-24 16:25:57.166859', 'mouse', 79.0)
(5, '2021-11-24 16:25:57.224900', 'teclado', 79.0)
(6, '2021-11-24 16:25:57.286443', 'teclado', 73.0)
(7, '2021-11-24 16:25:57.339480', 'monitor', 53.0)
(8, '2021-11-24 16:25:57.397521', 'mouse', 54.0)
(9, '2021-11-24 16:25:57.512102', 'mouse', 64.0)
(10, '2021-11-24 16:25:57.584154', 'monitor', 65.0)
(11, '2021-11-24 16:25:57.718247', 'memória', 85.0)
(12, '2021-11-24 16:25:57.877360', 'SSD', 96.0)
(13, '2021-11-24 16:25:57.976930', 'memória', 85.0)
(14, '2021-11-24 16:25:58.103018', 'SSD', 87.0)
(15, '2021-11-24 16:25:58.226605', 'gabinete', 74.0)
(16, '2021-11-24 16:25:58.339185', 'SSD', 96.0)
(17, '2021-11-24 16:25:58.512806', 'memória', 61.0)
(18, '2021-11-24 16:25:58.626886', 'memória', 68.0)
(19, '2021-11-24 16:25:58.789501', 'mouse', 97.0)
(20, '2021-11-24 16:25:58.954118', 'mon

In [29]:
df = cria_data_frame()
df

0                           1         2     3
0    1  2021-11-24 16:25:56.983730   monitor  84.0
1    2  2021-11-24 16:25:57.074294   teclado  51.0
2    3  2021-11-24 16:25:57.118325  gabinete  80.0
3    4  2021-11-24 16:25:57.166859     mouse  79.0
4    5  2021-11-24 16:25:57.224900   teclado  79.0
5    6  2021-11-24 16:25:57.286443   teclado  73.0
6    7  2021-11-24 16:25:57.339480   monitor  53.0
7    8  2021-11-24 16:25:57.397521     mouse  54.0
8    9  2021-11-24 16:25:57.512102     mouse  64.0
9   10  2021-11-24 16:25:57.584154   monitor  65.0
10  11  2021-11-24 16:25:57.718247   memória  85.0
11  12  2021-11-24 16:25:57.877360       SSD  96.0
12  13  2021-11-24 16:25:57.976930   memória  85.0
13  14  2021-11-24 16:25:58.103018       SSD  87.0
14  15  2021-11-24 16:25:58.226605  gabinete  74.0
15  16  2021-11-24 16:25:58.339185       SSD  96.0
16  17  2021-11-24 16:25:58.512806   memória  61.0
17  18  2021-11-24 16:25:58.626886   memória  68.0
18  19  2021-11-24 16:25:58.789501     mouse  97.0
19  20  2021-11-24 16:25:58.954118   monitor  79.0

# Fim